image: node:14 # Default image for pipelines

pipelines:
  default:
    - step:
        name: Run Security Tests
        image: cypress/included:4.4.1
        script:
          - echo "Running Security Tests..."
          - npm install -g snyk
          - snyk auth $SNYK_TOKEN
          - npm run security-test
    - step:
        name: Build and Deploy
        image: hashicorp/terraform:1.5.6
        script:
          - apk add --no-cache bash py-pip
          - apk add --virtual=build gcc libffi-dev musl-dev openssl-dev python3-dev
          - pip --no-cache-dir install -U pip
          - pip --no-cache-dir install azure-cli
          - echo "Logging in to Azure..."
          - az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
          - export VERSION=$BITBUCKET_BUILD_NUMBER
          - chmod +x ./scripts/deploy.sh
          - ./scripts/deploy.sh

  custom:
    CypressTest: # Defining custom pipeline for Cypress Test
      - step:
          name: Cypress Test
          image: cypress/included:4.4.1
          script:
            - echo "Running Cypress Tests..."
            - npm install
            - npm run test # Ensure you have a script named "test" in your package.json

    Destroy: # Defining custom pipeline for Destroying Terraform resources
      - step:
          name: Destroy
          image: hashicorp/terraform:1.5.6
          script:
            - apk add --no-cache bash py-pip
            - apk add --virtual=build gcc libffi-dev musl-dev openssl-dev python3-dev
            - pip --no-cache-dir install -U pip
            - pip --no-cache-dir install azure-cli
            - echo "Logging in to Azure..."
            - az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
            - cd ./scripts
            - terraform init
            - terraform destroy -auto-approve
